spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@mongodb:27017/paymentdb?authSource=admin

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

jwt:
  secret: ${JWT_SECRET:bXktc3VwZXItc2VjcmV0LWtleS1teS1zdXBlci1zZWNyZXQta2V5LTEyMzQ=}
